name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: install flit
        run: pip install flit
      - name: publish
        env:
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: bash ./scripts/publish.sh
