# Generated by Django 2.1.3 on 2020-03-24 12:21

from django.db import migrations, models
# import mailqueue

class Migration(migrations.Migration):

    initial = True

    dependencies = [
       ('mailqueue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creació')),
                ('text_identifier', models.CharField(max_length=100, unique=True, verbose_name='identificador')),
                ('subject', models.CharField(max_length=250, verbose_name='assumpte')),
                ('body', models.TextField(verbose_name='cos')),
                ('default_template_path', models.CharField(blank=True, max_length=250, null=True, verbose_name='plantilla per defecte')),
            ],
        ),
    ]
