[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm>=6.2",
    "grpcio>=1.43.0",
    "grpcio-tools>=1.43.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/qwilfish/_version.py"
local_scheme = "no-local-version"
