CONFIGMAP_FILE_ENVIRONMENT = "PYMS_CONFIGMAP_FILE"
CONFIGMAP_FILE_ENVIRONMENT_LEGACY = "CONFIGMAP_FILE"

DEFAULT_CONFIGMAP_FILENAME = "config.yml"

CRYPT_FILE_KEY_ENVIRONMENT = "PYMS_KEY_FILE"
CRYPT_FILE_KEY_ENVIRONMENT_LEGACY = "KEY_FILE"

DEFAULT_KEY_FILENAME = "key.key"

LOGGER_NAME = "janusmskit"

CONFIG_BASE = "janusmskit.config"

SERVICE_BASE = "janusmskit.services"

CRYPT_BASE = "janusmskit.crypt"

PYMS_CONFIG_WHITELIST_KEYWORDS = ["config", "services", "crypt"]
