name: run-canary-tests
on:
  schedule:
    - cron: '0 8 * * *'
jobs:
  canary_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Run Canary Tests
      env:
        HOPSKOTCH_USERNAME: ${{ secrets.HOPSKOTCH_USERNAME }}
        HOPSKOTCH_PASSWORD: ${{ secrets.HOPSKOTCH_PASSWORD }}
      run: python tom_scimma/tests/run_canary_tests.py
