[tool.poetry]
name = "ab_nic_sw"
version = "0.2.1"
description = "Alveo Burst NIC Control Software"
authors = ["Andrew Bolin, Jason van Aardt, CSIRO"]
license = "CSIRO Open Source Software Licence"
packages = [{include = "ab_nic_sw", from = "src"}]

[tool.poetry.dependencies]
python = "^3.7"
ska-low-cbf-fpga = "^0.12.0"
dpkt = "^1.9.7"
scapy = "^2.4.5"
rich = "^12.0.1"
fxpmath = "^0.4.5"

[tool.poetry.dev-dependencies]
pre-commit = "^2.16.0"
black = "^21.12b0"
pytest = "^6.2.5"
isort = "^5.9.3"
pylint = "^2.12.2"

[tool.poetry.scripts]
change_port = "ab_nic_sw.change_port:main"
compare_pcap = "ab_nic_sw.compare_pcap:main"
eth_interface_rate = "ab_nic_sw.eth_interface_rate:main"
pcap_to_hbm = "ab_nic_sw.pcap_to_hbm:main"

[[tool.poetry.source]]
name = "ska"
url = "https://artefact.skao.int/repository/pypi-internal/simple"
secondary = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
src_paths = ["src/ab_nic_sw", "tests"]
