"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.step_type import StepType


class TestStepType(unittest.TestCase):
    """StepType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStepType(self):
        """Test StepType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StepType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
