"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.analyze_grad_type_enum import AnalyzeGradTypeEnum
from openapi_client.model.data_state_type import DataStateType
from openapi_client.model.job_type import JobType
from openapi_client.model.plan_request import PlanRequest
from openapi_client.model.sample_identity import SampleIdentity
from openapi_client.model.training_params import TrainingParams
from openapi_client.model.visualization_target import VisualizationTarget
globals()['AnalyzeGradTypeEnum'] = AnalyzeGradTypeEnum
globals()['DataStateType'] = DataStateType
globals()['JobType'] = JobType
globals()['PlanRequest'] = PlanRequest
globals()['SampleIdentity'] = SampleIdentity
globals()['TrainingParams'] = TrainingParams
globals()['VisualizationTarget'] = VisualizationTarget
from openapi_client.model.add_job_params import AddJobParams


class TestAddJobParams(unittest.TestCase):
    """AddJobParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddJobParams(self):
        """Test AddJobParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddJobParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
