"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ui_func_instance import UiFuncInstance
globals()['UiFuncInstance'] = UiFuncInstance
from openapi_client.model.test_custom_loss_params import TestCustomLossParams


class TestTestCustomLossParams(unittest.TestCase):
    """TestCustomLossParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCustomLossParams(self):
        """Test TestCustomLossParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TestCustomLossParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
