
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T11:29:38+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "118294b076260a1bafc9a0799209504ae30eda39",
 "version": "v0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
