
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T13:46:06+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "28412f90978f0be4ef6eaa1eb6b494e9e5a3aebb",
 "version": "0.0.71.post0.dev80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
