[tool.poetry]
name = "tatuarvela-magic"
version = "3.1.3"
description = "A tool for simplifying repeated command line tasks"
authors = ["Tatu Arvela <tatu.arvela@nitor.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/TatuArvela/magic"
packages = [
    {include = "magic"}
]

[tool.poetry.dependencies]
click = "^8.0.0"
fastjsonschema = "^2.15.0"
python = "^3.7"
importlib-metadata = "^4.6.3"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "^21.7b0"
coverage = "^5.5"
isort = "^5.7.0"
pre-commit = "^2.11.1"
pylint = "^2.10.2"
pytest = "^6.2.3"
snapshottest = "^0.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
magic = "magic:main"

[tool.isort]
profile = "black"
skip_gitignore = true
skip = ["tests/snapshots/"]

[tool.black]
extend-exclude = 'tests/snapshots/.*\.py'

[tool.pylint.messages_control]
disable = [
    "C0330", # for black compatibility
    "C0326", # for black compatibility
    "C0114",
    "C0115",
    "C0116",
    "C0301",
    "C0415",
]

[tool.pylint.format]
max-line-length = "88"

[tool.pytest]
testpaths = [
    "tests",
]

[tool.coverage.run]
source = ['magic']
