"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.custom_loss_functions import CustomLossFunctions
from openapi_client.model.test_status import TestStatus
globals()['CustomLossFunctions'] = CustomLossFunctions
globals()['TestStatus'] = TestStatus
from openapi_client.model.custom_loss_version import CustomLossVersion


class TestCustomLossVersion(unittest.TestCase):
    """CustomLossVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustomLossVersion(self):
        """Test CustomLossVersion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CustomLossVersion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
