"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recover_visualizations_params import RecoverVisualizationsParams


class TestRecoverVisualizationsParams(unittest.TestCase):
    """RecoverVisualizationsParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverVisualizationsParams(self):
        """Test RecoverVisualizationsParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverVisualizationsParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
