"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.84
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.analyzer_panel_layout import AnalyzerPanelLayout
from openapi_client.model.visualization_target_type import VisualizationTargetType
globals()['AnalyzerPanelLayout'] = AnalyzerPanelLayout
globals()['VisualizationTargetType'] = VisualizationTargetType
from openapi_client.model.visualization_target import VisualizationTarget


class TestVisualizationTarget(unittest.TestCase):
    """VisualizationTarget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVisualizationTarget(self):
        """Test VisualizationTarget"""
        # FIXME: construct object with mandatory attributes with example values
        # model = VisualizationTarget()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
