[tool.poetry]
name = "foresight"
version = "0.3.1"
description = "Time management tool."
authors = ["etschz <ethanschmitz214@gmail.com>"]
license = "MIT"

readme = "README.md"
repository = "https://github.com/etschz/foresight"

keywords = ["time", "harvest", "zoom", "calendar", "foresight"]

classifiers = ["Topic :: Software Development :: Libraries :: Python Modules"]

[tool.poetry.dependencies]
python = "^3.8"
google-api-python-client = "^2.42.0"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.5.1"
pendulum = "^2.1.2"
cleo = "1.0.0a4"
tomlkit = "^0.10.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pytest = "^7.1.1"
tox = "^3.24.5"
pytest-cov = "^3.0.0"
pytest-sugar = "^0.9.4"
httpretty = "^1.1.4"
ipykernel = "^6.10.0"
black = {version = "^22.3.0", allow-prereleases = true}
pytest-mock = "^3.7.0"

[tool.poetry.scripts]
foresight = "foresight.console.application:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
