# Generated by Django 3.2.12 on 2022-03-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calender", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="register",
            name="is_present",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
