
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T11:10:28+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2062122728957f376ce4080ca121c7101a1c5eaf",
 "version": "0.7.1.post.dev479"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
