# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['automation_engine', 'automation_engine.mqtt']

package_data = \
{'': ['*']}

install_requires = \
['gmqtt>=0.6.9,<0.7.0', 'pydantic>=1.8.2,<2.0.0', 'toml>=0.10.2,<0.11.0']

extras_require = \
{'all': ['hue2mqtt>=0.2.2,<0.3.0'], 'hue': ['hue2mqtt>=0.2.2,<0.3.0']}

setup_kwargs = {
    'name': 'automation-engine',
    'version': '0.4.0a1',
    'description': 'Automation Engine powered by MQTT',
    'long_description': '# Automation Engine\n\nAutomation Engine powered by MQTT\n\n## Contributions\n\nThis project is released under the MIT Licence. For more information, please see LICENSE.\n\nThe CONTRIBUTORS file can be generated by executing CONTRIBUTORS.gen. This generated file contains a list of people who have contributed to Automation Engine.\n\n',
    'author': 'Dan Trickey',
    'author_email': 'contact@trickey.io',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/trickeydan/automation-engine',
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'python_requires': '>=3.8,<4.0',
}


setup(**setup_kwargs)
