
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-12-20T14:59:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "61f40c40d01a387ddbde3ac2d3f90921c4d7bae1",
 "version": "2.9.43.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
