
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T15:13:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4ae93267ebbc07292b414b9566d5b6da7cda9905",
 "version": "2022.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
