[tool.poetry]
name = "tf-annotations"
version = "0.3.0"
description = "Tool to report on annotations such as TODO"
authors = ["Russell Whelan <russell.whelan+python@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
tf-annotations = "tf_annotations.cmd:cli"
