BASE_URL = "http://gradus.kiedanski.com"

[token]
url = "/token"
mode = "post"
content-type = "application/x-www-form-urlencoded"

[users]
url = "/users/me"
mode = "get"
content-type = "application/json"

[course]
url = "/course"
mode = "post"
content-type = "application/json"

[exercise]
url = "/exercise"
mode = "post"
content-type = "application/json"

[task]
url = "/task"
mode = "post"
content-type = "application/json"

[attempt]
url = "/attempt/"
mode = "post"
content-type = "application/json"
