[tool.poetry]
name = "pytypeclass"
version = "0.1.1"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]
include = ["pytypeclass/py.typed"]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"
ipython = "^8.0.1"
black = "^22.1.0"
pre-commit = "^2.17.0"
jupyter = "^1.0.0"
jupytext = "^1.13.7"
jupyter-http-over-ws = "^0.0.8"
mypy = "^0.931"
pyre-check = "^0.9.10"
flake8 = "^4.0.1"
pdoc3 = "^0.10.0"
pyright = "^1.1.225"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.mypy]
exclude = ['readme\.py']
