[tool.poetry]
name = "embed-python-manager"
version = "0.2.7"
description = "Download and manage embedded python versions."
readme = "README.md"
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
lk-logger = "^5.0.1"
lk-utils = "^2.2.0"
pyyaml = ""

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
