[tool.poetry]
name        = "aiolastfm"
version     = "0.0.2"
description = "An async wrapper for the last.fm API."
authors     = ["Axel <axelancerr@gmail.com>"]
license     = "MIT"
readme      = "README.md"

homepage        = "https://github.com/Axelware/aiolastfm"
repository      = "https://github.com/Axelware/aiolastfm"
documentation   = "https://aiolastfm.readthedocs.io/en/latest/"

keywords = [
    "lastfm", "api", "wrapper", "async"
]
classifiers = [
    "Framework :: AsyncIO",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 2 - Pre-Alpha",
    "Programming Language :: Python :: Implementation :: CPython",
    "Operating System :: OS Independent",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Typing :: Typed"
]

packages = [
    { include = "aiolastfm" },
    { include = "aiolastfm/**/*.py" },
    { include = "aiolastfm/py.typed" },
]
include = [
    "LICENSE",
    "README.md"
]


[tool.poetry.dependencies]
python  = "^3.10.0"
aiohttp = "^3.8.0"

orjson = { version = "^3.6.0", optional = true }

sphinx              = { version = "^4.5.0",       optional = true }
sphinxcontrib-trio  = { version = "^1.1.0",       optional = true }
sphinx-copybutton   = { version = "^0.5.0",       optional = true }
sphinxext-opengraph = { version = "^0.6.0",       optional = true }
furo                = { version = "^2022.3.0",    optional = true }


[tool.poetry.dev-dependencies]
isort = "*"


[tool.poetry.extras]
speed   = ["orjson"]
docs    = ["sphinx", "sphinxcontrib-trio", "sphinx-copybutton", "sphinxext-opengraph", "furo"]


[tool.poetry.urls]
"Issue Tracker" = "https://github.com/Axelware/aiolastfm/issues"
"Discord"       = "https://discord.com/invite/w9f6NkQbde"


[tool.isort]
line_length                 = 120
multi_line_output           = 3
lines_after_imports         = 2
combine_star                = true
include_trailing_comma      = true
star_first                  = true
import_heading_future       = "Future"
import_heading_stdlib       = "Standard Library"
import_heading_thirdparty   = "Packages"
import_heading_firstparty   = "My stuff"
import_heading_localfolder  = "My stuff"


[build-system]
requires        = ["poetry_core>=1.0.0"]
build-backend   = "poetry.core.masonry.api"


[tool.pyright]
include                 = ["aiolastfm", "docs"]
verboseOutput           = false
pythonVersion           = "3.10"
typeCheckingMode        = "strict"
useLibraryCodeForTypes  = true

reportMissingTypeStubs = false
reportPrivateImportUsage = false
reportPrivateUsage = false
reportFunctionMemberAccess = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUnknownArgumentType = false
reportImportCycles = false
