[tool.poetry]
name = "pyportable-crypto"
version = "1.0.1"
description = "Crypto plugin for pyportable-installer project."
authors = ["Likianta <likianta@foxmail.com>"]
license = "MIT"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple/"
default = true

[tool.poetry.dependencies]
python = "^3.8"
lk-logger = "^5.0.1"
lk-utils = "^2.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
