
name: PyPI

on:
  release:
    types: [created]


jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      if: startsWith(github.ref, 'refs/tags')
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flit

    - name: Build and Publish package
      run: python -m flit publish
      env:
        FLIT_USERNAME: __token__
        FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
