[tool.poetry]
name = "Hell_package"
version = "0.1.0"
description = "\" \""
authors = ["Oussama BATATA"]
license = "MIT"
packages = [
    { include = "my_package" }
 ]
exclude = ["my_package/config_file.yaml"]

[tool.poetry.dependencies]
python = "^3.9"
Unidecode = "^1.3.4"
requests = "^2.13.0"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
