
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-26T09:46:33+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "36a087aba3c2813a98bb383fa59a9d4f7f8a339b",
 "version": "4.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
