
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T17:47:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "0416c736c5fb2458b3b5f3b15b95dba914028a82",
 "version": "v0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
