[tool.coverage]
report.fail_under = 90

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true

[tool.poetry]
name = "repid"
version = "0.2.3"
description = "Async Redis queue for Python."
authors = ["aleksul <aleksandrsulimov@bk.ru>"]
repository = "https://github.com/aleksul/repid"
documentation = "https://aleksul.github.io/repid"
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
redis = "^4.2.0"
orjson = "^3.6.7"

[tool.poetry.dev-dependencies]
# sort
black = "^22.1.0"
isort = "^5.10.1"
# lint
mypy = "^0.910"
types-orjson = "^3.6.2"
types-redis = "^4.1.18"
flake8 = "^4.0.1"
flake8-bugbear = "^21.11.29"
flake8-builtins = "^1.5.3"
flake8-pytest-style = "^1.6.0"
# test
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
pytest-cov = "^3.0.0"
pytest-docker = "^0.10.3"
# pre-commit
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
