[tool.poetry]
name = "leapcli"
version = "0.2.20"
description = "Tensorleap CLI"
authors = ["Assaf Lavie <assaf.lavie@tensorleap.ai>", "Idan Yogev <idan.yogev@tensorleap.ai>", "dorhar <doron.harnoy@tensorleap.ai>"]
license = "MIT"
repository = "https://github.com/tensorleap/cli"
homepage = "https://github.com/tensorleap/cli"
include = ["templates/**/*", "cli.py"]


[tool.poetry.dependencies]
python = ">=3.6.1,<3.7"
docopt = "^0.6.2"
toml = "^0.10.2"
GitPython = "^3.1.18"
semver = "^2.13.0"
pytest-mock = "^3.6.1"
requests = "^2.26.0"
python-json-logger = "^2.0.2"
tensorleap-openapi-client = "1.1.10"
luddite = "^1.0.2"
code-loader = "0.1.15"
prettytable = "2.5.0"
leap-model-parser = "^0.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"
pytest-watch = "^4.2.0"
grappa = "^1.0.1"
pylint = "^2.8.3"
rope = "^0.19.0"
setuptools = "<50.0.0"
sh = "^1.14.2"
pylint-pytest = "^1.1.2"
tensorflow = "^2.4.0"
pytest-cov = "^2.12.1"
httpretty = "^1.1.4"
opencv-python = "4.5.1.48"
Pillow = "8.4.0"
scikit-learn = "0.23.2"
scikit-image = "0.17.2"

[tool.poetry.scripts]
leap = "cli:__main__"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = ["ignore:.*the imp module.*:DeprecationWarning"]
