# See https://setuptools.pypa.io/en/latest/userguide/quickstart.html
# for info on how to lay this out
[build-system]
requires = ["setuptools", "wheel", "genson"]
build-backend = "setuptools.build_meta"