# Generated by Django 2.2.24 on 2021-08-24 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0012_auto_20210823_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='sponsored_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='minutes.NativeAd'),
        ),
    ]
