[tool.poetry]
name = "mpsprep"
version = "0.1.1"
description = "State preparation for quantum computing using the Matrix Product States approach."
authors = ["Prithvi Gundlapalli, Junyi Lee"]

[tool.poetry.dependencies]
python = ">=3.7,<3.10"
numpy = "1.21"
scipy = "1.7"
matplotlib = "3.5"
tqdm = "4.60"
ipykernel = "^6.9.2"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]
coverage = ">=6"
tox = ">=3.24"
flake8 = ">=4"
pytest-cov = "^3.0.0"
pytest = "^7.1.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
