[tool.poetry]
name = "gwdc-python"
version = "0.3.2"
description = "API for GWDC modules"
authors = ["Thomas Reichardt <treichardt@swin.edu.au>"]
license = "MIT"
readme = "README.rst"
repository = "https://github.com/gravitationalwavedc/gwdc_python"
include = ["LICENSE",]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.25.1"
jwt = "^1.2.0"
requests-toolbelt = "^0.9.1"
tqdm = "^4.61.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
requests-mock = "^1.8.0"
pyflakes = "^2.3.1"
flake8 = "^3.9.2"
coverage = "^5.5"
pytest-cov = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
