on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Run tests

jobs:
  test:
    name: nose tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7' ]
    env:
      HTTPOBS_BROKER_URL: fakebrokerurl
      HTTPOBS_DATABASE_HOST: fakehost
      HTTPOBS_DATABASE_PASS: foo
      HTTPOBS_DATABASE_USER: bar
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install . -r requirements.txt
      - name: Run flake8 tests
        run: flake8 --config .flake8 httpobs
      - name: Run nose tests
        run: nosetests httpobs/tests -e insert_test_result -e scored_test -e select_test_results -e test_retrieve --with-coverage --cover-package=httpobs

