[tool.poetry]
name = "vote4film"
version = "1.7.5"
description = "Easy scheduling for regular film nights"
homepage = "https://github.com/Fustra/vote4film/"
repository = "https://github.com/Fustra/vote4film/"
readme = "README.md"
authors = ["QasimK <noreply@QasimK.io>"]
license = "AGPL-3.0"
classifiers = [
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Environment :: No Input/Output (Daemon)",
    "Natural Language :: English",
    "Topic :: Internet :: WWW/HTTP :: WSGI :: Application",
]
packages = [
    { include = "calender", from = "src"},
    { include = "films", from = "src" },
    { include = "schedule", from = "src" },
    { include = "vote4film", from = "src" },
    { include = "votes", from = "src" },
    { include = "web", from = "src" },
    { include = "manage.py", from = "src" },
]

[tool.poetry.scripts]
manage = 'manage:main'

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.2"
django-environ = "^0.8.1"
django-extensions = "^3.1.3"
requests = "^2.25.1"
lxml = "^4.6.3"
xdg = "^5.0.2"
psycopg2 = {version = "^2.8.6", optional = true}
pyhumps = "^3.0.2"
bbfcapi = "^3.0.1"
sentry-sdk = {version = "^1.1", optional = true}

[tool.poetry.dev-dependencies]
# Checks
autoflake = "^1.4"
black = "22.3.0"
isort = "^5.8"
bandit = "^1.6"
pyflakes = "^2.3"
safety = "^1.9"
# Development helpers
django-debug-toolbar = "^3.2"
werkzeug = "^2.0"
# Tests
pytest = "^7.1"
pytest-django = "^4.3"
responses = "^0.20"
factory_boy = "^3.1"

[tool.poetry.extras]
postgres = ["psycopg2"]
sentry = ["sentry-sdk"]

[tool.black]
target-version = ['py38']

[tool.isort]
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
