# Generated by Django 2.2.24 on 2021-08-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_minute_last_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='ready_to_publish',
            field=models.BooleanField(default=False),
        ),
    ]
