# Generated by Django 2.2.24 on 2021-08-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_nativead'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nativead',
            old_name='content',
            new_name='body',
        ),
    ]
