# Generated by Django 2.2.24 on 2021-08-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0013_edition_sponsored_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edition',
            old_name='sponsored_card',
            new_name='native_ad',
        ),
    ]
