# Generated by Django 2.2.24 on 2021-08-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0014_auto_20210824_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='nativead',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
