
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T03:23:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b27806868e8902f4ba7274e02154a8c7f4aa637",
 "version": "1.16.0.post.dev314"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
