
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T12:27:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "04a6d915fad7cc7922389a31f924cf0c4de28d9c",
 "version": "2.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
