[project]
name = "nonebot-plugin-wordle-daily"
version = "0.1.0"
description = ""
authors = [
    { name = "iyume", email = "iyumelive@gmail.com" },
]
dependencies = [
    "nonebot2>=2.0.0b1",
    "nonebot-adapter-onebot>=2.0.0b1",
    "Pillow>=8.4.0",
    "nonebot-plugin-params>=0.1.0",
]
requires-python = ">=3.7.3"
readme = "README.md"
keywords = [
    "nonebot",
    "onebot",
    "wordle",
]

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/iyume/nonebot-plugin-wordle"
repository = "https://github.com/iyume/nonebot-plugin-wordle"

[project.optional-dependencies]

[tool.pdm]
editable-backend = "editables"

[tool.pdm.dev-dependencies]
dev = [
    "mypy>=0.931",
    "black>=22.1.0",
    "pipdeptree>=2.2.1",
    "types-Pillow>=9.0.6",
]

[tool.black]
line-length = 88

[tool.isort]
profile = "black"

[build-system]
requires = [
    "pdm-pep517",
]
build-backend = "pdm.pep517.api"
