[tool.poetry]
name = "hotedit"
version = "0.9.0"
description = "Automatically find and launch an editor with a stream of text to edit; then save"
authors = ["Cory Dodt <corydodt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest = { version = "^5.2", optional = true }
pytest-cov = { version = "^3.0.0", optional = true }
pytest-flakes = { version = "^4.0.5", optional = true }

[tool.poetry.dev-dependencies]
black = "^22.1.0"

[tool.poetry.extras]
test = [ "pytest", "pytest-coverage", "pytest-flakes" ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
