[project]
name = "wcore_py"
classifiers = ["Development Status :: 3 - Alpha", "Programming Language :: Rust", "Topic :: Education"]
authors = [
        {name = "James Butcher", email = "jamesbutcher@duck.com"},
]
readme = "README.md"


[build-system]
requires = ["maturin>=0.12,<0.13"]
build-backend = "maturin"
