[tool.poetry]
name = "rpaframework-aws"
version = "0.1.0"
description = "AWS library for RPA Framework"
authors = ["RPA Framework <rpafw©robocorp.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
