"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.analyze_type_enum import AnalyzeTypeEnum
from openapi_client.model.job_params_options_params import JobParamsOptionsParams
globals()['AnalyzeTypeEnum'] = AnalyzeTypeEnum
globals()['JobParamsOptionsParams'] = JobParamsOptionsParams
from openapi_client.model.job_params_options import JobParamsOptions


class TestJobParamsOptions(unittest.TestCase):
    """JobParamsOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobParamsOptions(self):
        """Test JobParamsOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = JobParamsOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
