"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.project import Project
from openapi_client.model.version import Version
globals()['Project'] = Project
globals()['Version'] = Version
from openapi_client.model.save_project_response import SaveProjectResponse


class TestSaveProjectResponse(unittest.TestCase):
    """SaveProjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSaveProjectResponse(self):
        """Test SaveProjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SaveProjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
