"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.image_scatter_label import ImageScatterLabel
from openapi_client.model.text_scatter_label import TextScatterLabel
from openapi_client.model.word_scatter_label import WordScatterLabel
globals()['ImageScatterLabel'] = ImageScatterLabel
globals()['TextScatterLabel'] = TextScatterLabel
globals()['WordScatterLabel'] = WordScatterLabel
from openapi_client.model.scatter_label import ScatterLabel


class TestScatterLabel(unittest.TestCase):
    """ScatterLabel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScatterLabel(self):
        """Test ScatterLabel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScatterLabel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
