"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.remove_project_from_dashboard_params import RemoveProjectFromDashboardParams


class TestRemoveProjectFromDashboardParams(unittest.TestCase):
    """RemoveProjectFromDashboardParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRemoveProjectFromDashboardParams(self):
        """Test RemoveProjectFromDashboardParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RemoveProjectFromDashboardParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
