"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.kibana_dashboard import KibanaDashboard


class TestKibanaDashboard(unittest.TestCase):
    """KibanaDashboard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKibanaDashboard(self):
        """Test KibanaDashboard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = KibanaDashboard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
