"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.kibana_dashboard import KibanaDashboard
globals()['KibanaDashboard'] = KibanaDashboard
from openapi_client.model.get_kibana_dashboards_response import GetKibanaDashboardsResponse


class TestGetKibanaDashboardsResponse(unittest.TestCase):
    """GetKibanaDashboardsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetKibanaDashboardsResponse(self):
        """Test GetKibanaDashboardsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetKibanaDashboardsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
