"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.strip_type import StripType


class TestStripType(unittest.TestCase):
    """StripType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStripType(self):
        """Test StripType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StripType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
