"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.recover_visualizations_response import RecoverVisualizationsResponse


class TestRecoverVisualizationsResponse(unittest.TestCase):
    """RecoverVisualizationsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecoverVisualizationsResponse(self):
        """Test RecoverVisualizationsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = RecoverVisualizationsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
