"""
    server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.80
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.version import Version
globals()['Version'] = Version
from openapi_client.model.get_branch_versions_response import GetBranchVersionsResponse


class TestGetBranchVersionsResponse(unittest.TestCase):
    """GetBranchVersionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBranchVersionsResponse(self):
        """Test GetBranchVersionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBranchVersionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
