[tool.poetry]
name = "difftree"
version = "0.1.1"
description = "Diff two directories recursively"
readme = "README.md"
authors = ["Malthe Jørgensen <malthe.jorgensen@gmail.com>"]
homepage = "https://github.com/malthejorgensen/difftree"
repository = "https://github.com/malthejorgensen/difftree"
license = "MIT"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Utilities",
    "Topic :: System :: Filesystems",
    "Topic :: System :: Archiving :: Mirroring",
    "Topic :: System :: Recovery Tools",
]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
difftree = "difftree.main:entry"
