[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
name = "pAsynCrawler" 
version = "0.1.11" # official version

authors = [{name = "Michael Hsieh", email = "m9810223@gmail.com"}]
description = ""

requires-python = ">=3.6,<4"

dependencies = [
  "aiohttp >=3.8.1",
]

classifiers = [
  "Environment :: Web Environment",
  "Framework :: aiohttp",
  "Framework :: AsyncIO",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Internet",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development",
]
license = {file = "LICENSE"}
readme = "README.md"

[project.optional-dependencies]
demo = [
  "beautifulsoup4 >=4.10.0",
]

[project.urls]
"Bug Tracker" = "https://github.com/m9810223/pAsynCrawler/issues"
Source = "https://github.com/m9810223/pAsynCrawler"
documentation = "https://github.com/m9810223/pAsynCrawler#readme"
homepage = "https://github.com/m9810223/pAsynCrawler"

[tool.poetry]
authors = [" "]
description = ""
name = "pAsynCrawler"
version = "0.1.11-dev"

[tool.poetry.dependencies]
aiohttp = "^3.8.1"
python = ">3.7,<4"

[tool.poetry.dev-dependencies]
black = {version = "^22.3.0", allow-prereleases = true}
bs4 = "^0.0.1"
