
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T09:59:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3cf0c393a2cbe3e387fcfcb66a7899ab8d39e43b",
 "version": "0.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
