[build-system]
requires = ["setuptools>=51", "setuptools_scm>=6.3.2", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.mypy]
disallow_untyped_defs = true

[[tool.mypy.overrides]]
module = "setuptools_scm"
ignore_missing_imports = true
