[package]
name = "whispool"
version = "0.1.1"
edition = "2021"

[lib]
name = "whispool"
crate-type = ["cdylib"]
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
scoped_threadpool = "0.1.9"
uuid = { version = "0.8", features = ["serde", "v4"] }
colored = "2"

[dependencies.pyo3]
version = "0.15.1"
features = ["extension-module"]

[package.metadata.maturin]
python-source = "python"
