
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-25T17:10:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c5984c35f38074655565d97ffaed7f8f7c42193a",
 "version": "0.0.71.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
