
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T07:27:52-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "ac26b8a8abb89eeb45d70f43d746d0d870852e68",
 "version": "0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
