[tool.poetry]
name = "pygrove"
version = "0.1.1-alpha.7"
description = "Common data science imports based on pyforest, with a NLP focus"
authors = ["sileod <damien.sileo@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pyforest = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
