[tool.poetry]
name = "icloud-todotxt"
version = "0.1.4"
description = "Synchronize your local `todo.txt` with iCloud."
authors = ["David Härer <david@familie-haerer.de>"]
readme = "README.md"
homepage = "https://github.com/DavidHeresy/icloud-todotxt"

[tool.poetry.scripts]
icloud-todotxt = "icloud_todotxt.main:app"

[tool.poetry.dependencies]
python = "^3.9"
pyicloud = "^1.0.0"
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
pylint = "^2.13.4"
black = "^22.3.0"
anybadge = "^1.9.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
