# Generated by Django 3.1.6 on 2021-02-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='prefix',
            field=models.CharField(blank=True, db_index=True, max_length=1, verbose_name='prefix'),
        ),
    ]
