# Generated by Django 3.1.6 on 2021-02-07 09:39

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_option_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'category', 'true_label', 'false_label'), required_languages=(), virtual_fields=True),
        ),
    ]
