# Generated by Django 3.1.6 on 2021-02-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20210207_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_viewable',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Set checked if users can see survey.', verbose_name='published'),
        ),
    ]
