# Generated by Django 3.1.6 on 2021-02-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20210207_1045'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, tag__in=(None, '', [], (), {})), fields=('survey', 'tag'), name='unique_tag'),
        ),
    ]
