# Generated by Django 3.1.6 on 2021-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20210207_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('TEXTFIELD', 'Textfield'), ('TEXTAREA', 'Textarea'), ('MATRIX_RADIO', 'Matrix radio'), ('MATRIX_CHECKBOX', 'Matrix checkbox'), ('TRUE_FALSE', 'True/False')], db_index=True, max_length=15, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='tag'),
        ),
    ]
