# Generated by Django 3.1.6 on 2021-02-08 01:02

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_auto_20210207_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='false_label',
        ),
        migrations.RemoveField(
            model_name='question',
            name='true_label',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='finish_url',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='finish_url_title',
        ),
        migrations.AlterField(
            model_name='option',
            name='orientation',
            field=models.CharField(choices=[('ROW', 'Row'), ('COLUMN', 'Column')], default='ROW', max_length=6, verbose_name='orientation'),
        ),
        migrations.AlterField(
            model_name='question',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('title', 'category'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('TEXTFIELD', 'Textfield'), ('TEXTAREA', 'Textarea'), ('MATRIX_RADIO', 'Matrix radio'), ('MATRIX_CHECKBOX', 'Matrix checkbox')], db_index=True, max_length=15, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='option',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, prefix__in=(None, '', [], (), {})), fields=('question', 'prefix'), name='unique_prefix'),
        ),
    ]
