# Generated by Django 3.1.6 on 2021-02-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_auto_20210208_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=10, verbose_name='tag'),
        ),
    ]
