# Generated by Django 3.1.6 on 2021-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_survey_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='tag'),
        ),
    ]
