# Generated by Django 3.1.6 on 2022-02-22 15:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_auto_20210211_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='time_limit',
            field=models.DurationField(blank=True, default=None, help_text='In minutes. Keep blank to infinite.', null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='duration'),
        )
    ]
