# Generated by Django 3.1.6 on 2022-02-25 09:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_auto_20220222_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='kind',
            field=models.CharField(choices=[('RADIO', 'Radio'), ('CHECKBOX', 'Checkbox'), ('DROPDOWN', 'Dropdown'), ('TEXTFIELD', 'Textfield'), ('TEXTAREA', 'Textarea'), ('MATRIX_RADIO', 'Matrix radio'), ('MATRIX_CHECKBOX', 'Matrix checkbox')], db_index=True, max_length=15, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='time_limit',
            field=models.DurationField(blank=True, default=None, help_text='In minutes. Keep blank to infinite.', null=True, validators=[django.core.validators.MinValueValidator(datetime.timedelta(seconds=60))], verbose_name='time limit'),
        ),
    ]
