[tool.poetry]
name = "ireval"
version = "0.1.1"
description = ""
authors = ["Jan-Christoph Klie  <git@mrklie.com>"]
readme = "README.md"
homepage = "https://github.com/jcklie/ireval"
repository = "https://github.com/jcklie/ireval"
keywords = ["information retrieval", "metrics", "machine learning"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
include = ["README.md"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.22.3"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
poethepoet = "^0.13.1"
pytrec-eval-terrier = "^0.5.2"
pytest = "^7.1.1"

[tool.poe.tasks]
black = "black -l 120 ireval/ tests/"
isort = "isort --profile black ireval/ tests/"
format = ["black", "isort"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
