
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-27T10:31:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d6c6309417ad80fcb0301ac209204ae6c2c15b62",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
