[tool.poetry]
name = "aliby"
version = "0.1.25"
description = "Process and analyse live-cell imaging data"
authors = ["Alan Munoz <alan.munoz@ed.ac.uk>"]
packages = [
    { include = "aliby" },
    { include = "extraction" },
]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.11"
numpy = "^1.16.0"
dask = "^2021.12.0"
pathos = "^0.2.8"
tqdm = "^4.62.3"
scikit-learn = "0.22.2.post1"
# more-itertools = "^8.12.0"
py-find-1st = "^1.1.5"
scikit-image = ">=0.18.1"
opencv-python = "*"
requests-toolbelt = "^0.9.1"
h5py = "2.10"
# tables = "^3.6.1"
imageio = "2.8.0"
omero-py = ">=5.6.2"
zeroc-ice = "3.6.5"
aliby-agora = "^0.2.23"
aliby-baby = "^0.1.7"
aliby-post = "^0.1.25"
p-tqdm = "^1.3.3"


[tool.poetry.dev-dependencies]
data-science-types = "^0.2.23"
black = "^21.12b0"
Sphinx = "^4.3.2"
pytest = "^6.2.5"
mypy = "^0.930"

[build-system]
requires = ["setuptools", "poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
