
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-04-01T09:40:35+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "95cb18c918da249b5e8ad43b78827b34e2bc3fb8",
 "version": "1.0.8rc7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
