
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-30T15:34:00+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7d03b55ae2e6c1c55d9094dba27243bf8b283ba2",
 "version": "2.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
