
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T15:07:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1e33fa2ca476d3afa2523f80ea7cb285a7b4b4a",
 "version": "v11.8.0-dev"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
