[build-system]
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab~=3.1", "jupyterlab_widgets~=1.0", "voila>=0.2,<0.4"]
build-backend = "jupyter_packaging.build_api"

[tool.jupyter-packaging.options]
skip-if-exists = ["voila_gridstack/labextension/static/style.js"]
ensured-targets = ["voila_gridstack/labextension/static/style.js", "voila_gridstack/labextension/package.json"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.tbump.version]
current = "0.3.0"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)
  ((?P<channel>a|b|rc|.dev)(?P<release>\d+))?
'''

[[tool.tbump.file]]
src = "voila_gridstack/__init__.py"

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[tool.jupyter-releaser]
skip = ["check-links"]

[tool.jupyter-releaser.hooks]
before-bump-version = ["python -m pip install jupyterlab~=3.1"]
before-build-npm = ["python -m pip install jupyterlab~=3.0", "jlpm clean", "jlpm build:prod"]
before-build-python = ["jlpm clean"]

[tool.jupyter-releaser.options]
version-cmd = "python scripts/bump-version.py --force"

[tool.check-manifest]
ignore = ["assets/**", "binder/**", "examples/**", "packages/**", "scripts/**", "voila_gridstack/labextension/**", "yarn.lock", ".*", "*.json", "lint-staged.config.js"]