# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    EnumDescriptor as google___protobuf___descriptor___EnumDescriptor,
    FieldDescriptor as google___protobuf___descriptor___FieldDescriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.enum_type_wrapper import (
    _EnumTypeWrapper as google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    NewType as typing___NewType,
    Optional as typing___Optional,
    Text as typing___Text,
    cast as typing___cast,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)


builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int


DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

DataTypeValue = typing___NewType('DataTypeValue', builtin___int)
type___DataTypeValue = DataTypeValue
DataType: _DataType
class _DataType(google___protobuf___internal___enum_type_wrapper____EnumTypeWrapper[DataTypeValue]):
    DESCRIPTOR: google___protobuf___descriptor___EnumDescriptor = ...
    UNSPECIFIED = typing___cast(DataTypeValue, 0)
    HIGH_VELOCITY = typing___cast(DataTypeValue, 1)
    HIGH_CARDINALITY = typing___cast(DataTypeValue, 2)
UNSPECIFIED = typing___cast(DataTypeValue, 0)
HIGH_VELOCITY = typing___cast(DataTypeValue, 1)
HIGH_CARDINALITY = typing___cast(DataTypeValue, 2)
type___DataType = DataType

class SideDataDef(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    data_type: type___DataTypeValue = ...
    qualifier: typing___Text = ...

    def __init__(self,
        *,
        data_type : typing___Optional[type___DataTypeValue] = None,
        qualifier : typing___Optional[typing___Text] = None,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions___Literal[u"data_type",b"data_type",u"qualifier",b"qualifier"]) -> None: ...
type___SideDataDef = SideDataDef

def: google___protobuf___descriptor___FieldDescriptor = ...
