
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-27T11:11:09-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "7bc1131e7c25057f2aec48e736e52eeb7d0d33db",
 "version": "0.0.88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
