[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm>=6.2",
    "scipy>=1.7",
    "biopandas",
    "rich"
]

build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
