[tool.poetry]
name = "pytest-shell"
version = "0.3.2"
description = "A pytest plugin to help with testing shell scripts / black box commands"
authors = ["Daniel Murray <daniel@darkdisco.net>"]
license = "MIT"
readme = "README.rst"
homepage = "https://hg.sr.ht/~danmur/pytest-shell"
repository = "https://hg.sr.ht/~danmur/pytest-shell"
documentation = "https://hg.sr.ht/~danmur/pytest-shell/browse/README.rst?rev=tip"

[tool.poetry.urls]
"Issues" = "https://todo.sr.ht/~danmur/pytest-shell"
"Changelog" = "https://hg.sr.ht/~danmur/pytest-shell/browse/CHANGES.rst?rev=tip"

[tool.poetry.plugins."pytest11"]
"shell" = "pytest_shell"

[tool.poetry.dependencies]
python = "^3.7"
where = "^1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
rich = "^10.12.0"  # Useful source of colours and odd characters for testing

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
