[tool.poetry]
name = "obsidian-telegram-reminders"
version = "0.1.0"
description = ""
authors = ["'Anton Shuvalov' <anton@shuvalov.info>"]
packages = [
    { include = "src" }
]

[tool.poetry.dependencies]
python = "^3.9"
regex = "^2022.3.15"
python-dotenv = "^0.19.0"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
obsidian-todos = "src.main:main"
