[tool.poetry]
name = "sem-desc"
version = "3.2.1"
description = "Package providing basic functionalities for the semantic modeling problem"
authors = ["Binh Vu <binh@toan2.com>"]
license = "MIT"
packages = [
    { include = "sm" }
]
include = [
]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
python-slugify = "^5.0.2"
lbry-rocksdb-optimized = "^0.8.1"
redis = "^3.5.3"
pyrsistent = "^0.17.3"
orjson = "^3.6.4"
loguru = "^0.5.3"
tqdm = "^4.60.0"
networkx = "^2.6.3"
matplotlib = "^3.4.2"
pydot = "^1.4.2"
ipython = "^8.0.1"
chardet = "^4.0.0"
ujson = "^5.1.0"
"ruamel.yaml" = "^0.17.9"
colorama = ">=0.4.4"
graph-wrapper = "~1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
