[build-system]
build-backend = "maturin"
requires = ["poetry_core>=1.0.0"]

[tool.poetry]
name = "egobox"
version = "0.1.0"
description = "Egor optimiser"
authors = ["relf <remi.lafage@onera.fr>"]

[tool.poetry.dependencies]
numpy = ">=1.18"
python = ">=3.7"

[tool.poetry.dev-dependencies]
pytest = "^6.2"