# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tecton_proto/data/internal_spark_cluster_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tecton_proto/data/internal_spark_cluster_status.proto',
  package='tecton_proto.data',
  syntax='proto2',
  serialized_options=b'\n\017com.tecton.dataP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n5tecton_proto/data/internal_spark_cluster_status.proto\x12\x11tecton_proto.data*\xf9\x01\n\x1aInternalSparkClusterStatus\x12)\n%INTERNAL_SPARK_CLUSTER_STATUS_UNKNOWN\x10\x00\x12)\n%INTERNAL_SPARK_CLUSTER_STATUS_HEALTHY\x10\x01\x12+\n\'INTERNAL_SPARK_CLUSTER_STATUS_UNHEALTHY\x10\x02\x12*\n&INTERNAL_SPARK_CLUSTER_STATUS_STARTING\x10\x03\x12,\n(INTERNAL_SPARK_CLUSTER_STATUS_NO_CLUSTER\x10\x04\x42\x13\n\x0f\x63om.tecton.dataP\x01'
)

_INTERNALSPARKCLUSTERSTATUS = _descriptor.EnumDescriptor(
  name='InternalSparkClusterStatus',
  full_name='tecton_proto.data.InternalSparkClusterStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SPARK_CLUSTER_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SPARK_CLUSTER_STATUS_HEALTHY', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SPARK_CLUSTER_STATUS_UNHEALTHY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SPARK_CLUSTER_STATUS_STARTING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INTERNAL_SPARK_CLUSTER_STATUS_NO_CLUSTER', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=77,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_INTERNALSPARKCLUSTERSTATUS)

InternalSparkClusterStatus = enum_type_wrapper.EnumTypeWrapper(_INTERNALSPARKCLUSTERSTATUS)
INTERNAL_SPARK_CLUSTER_STATUS_UNKNOWN = 0
INTERNAL_SPARK_CLUSTER_STATUS_HEALTHY = 1
INTERNAL_SPARK_CLUSTER_STATUS_UNHEALTHY = 2
INTERNAL_SPARK_CLUSTER_STATUS_STARTING = 3
INTERNAL_SPARK_CLUSTER_STATUS_NO_CLUSTER = 4


DESCRIPTOR.enum_types_by_name['InternalSparkClusterStatus'] = _INTERNALSPARKCLUSTERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
