# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summa/proto/consumer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asumma/proto/consumer.proto\x12\x0bsumma.proto\"N\n\x08\x43onsumer\x12#\n\rconsumer_name\x18\x01 \x01(\tR\x0c\x63onsumerName\x12\x1d\n\nindex_name\x18\x02 \x01(\tR\tindexNameb\x06proto3')



_CONSUMER = DESCRIPTOR.message_types_by_name['Consumer']
Consumer = _reflection.GeneratedProtocolMessageType('Consumer', (_message.Message,), {
  'DESCRIPTOR' : _CONSUMER,
  '__module__' : 'summa.proto.consumer_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.Consumer)
  })
_sym_db.RegisterMessage(Consumer)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONSUMER._serialized_start=43
  _CONSUMER._serialized_end=121
# @@protoc_insertion_point(module_scope)
