# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summa/proto/index.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17summa/proto/index.proto\x12\x0bsumma.proto\"K\n\x05Index\x12\x1d\n\nindex_name\x18\x01 \x01(\tR\tindexName\x12#\n\rindex_aliases\x18\x02 \x03(\tR\x0cindexAliases\"N\n\x16IndexDocumentOperation\x12\x1a\n\x08\x64ocument\x18\x01 \x01(\x0cR\x08\x64ocument\x12\x18\n\x07reindex\x18\x02 \x01(\x08R\x07reindex\"k\n\x0eIndexOperation\x12L\n\x0eindex_document\x18\x02 \x01(\x0b\x32#.summa.proto.IndexDocumentOperationH\x00R\rindexDocumentB\x0b\n\toperationb\x06proto3')



_INDEX = DESCRIPTOR.message_types_by_name['Index']
_INDEXDOCUMENTOPERATION = DESCRIPTOR.message_types_by_name['IndexDocumentOperation']
_INDEXOPERATION = DESCRIPTOR.message_types_by_name['IndexOperation']
Index = _reflection.GeneratedProtocolMessageType('Index', (_message.Message,), {
  'DESCRIPTOR' : _INDEX,
  '__module__' : 'summa.proto.index_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.Index)
  })
_sym_db.RegisterMessage(Index)

IndexDocumentOperation = _reflection.GeneratedProtocolMessageType('IndexDocumentOperation', (_message.Message,), {
  'DESCRIPTOR' : _INDEXDOCUMENTOPERATION,
  '__module__' : 'summa.proto.index_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.IndexDocumentOperation)
  })
_sym_db.RegisterMessage(IndexDocumentOperation)

IndexOperation = _reflection.GeneratedProtocolMessageType('IndexOperation', (_message.Message,), {
  'DESCRIPTOR' : _INDEXOPERATION,
  '__module__' : 'summa.proto.index_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.IndexOperation)
  })
_sym_db.RegisterMessage(IndexOperation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INDEX._serialized_start=40
  _INDEX._serialized_end=115
  _INDEXDOCUMENTOPERATION._serialized_start=117
  _INDEXDOCUMENTOPERATION._serialized_end=195
  _INDEXOPERATION._serialized_start=197
  _INDEXOPERATION._serialized_end=304
# @@protoc_insertion_point(module_scope)
