# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summa/proto/search_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n summa/proto/search_service.proto\x12\x0bsumma.proto\"^\n\x0eScoredDocument\x12\x1a\n\x08\x64ocument\x18\x01 \x01(\tR\x08\x64ocument\x12\x14\n\x05score\x18\x02 \x01(\x02R\x05score\x12\x1a\n\x08position\x18\x03 \x01(\rR\x08position\"t\n\rSearchRequest\x12\x1f\n\x0bindex_alias\x18\x01 \x01(\tR\nindexAlias\x12\x14\n\x05query\x18\x02 \x01(\tR\x05query\x12\x14\n\x05limit\x18\x03 \x01(\rR\x05limit\x12\x16\n\x06offset\x18\x04 \x01(\rR\x06offset\"\x92\x01\n\x0eSearchResponse\x12\x46\n\x10scored_documents\x18\x01 \x03(\x0b\x32\x1b.summa.proto.ScoredDocumentR\x0fscoredDocuments\x12\x19\n\x08has_next\x18\x02 \x01(\x08R\x07hasNext\x12\x1d\n\nindex_name\x18\x04 \x01(\tR\tindexName2P\n\tSearchApi\x12\x43\n\x06search\x12\x1a.summa.proto.SearchRequest\x1a\x1b.summa.proto.SearchResponse\"\x00\x62\x06proto3')



_SCOREDDOCUMENT = DESCRIPTOR.message_types_by_name['ScoredDocument']
_SEARCHREQUEST = DESCRIPTOR.message_types_by_name['SearchRequest']
_SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['SearchResponse']
ScoredDocument = _reflection.GeneratedProtocolMessageType('ScoredDocument', (_message.Message,), {
  'DESCRIPTOR' : _SCOREDDOCUMENT,
  '__module__' : 'summa.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.ScoredDocument)
  })
_sym_db.RegisterMessage(ScoredDocument)

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHREQUEST,
  '__module__' : 'summa.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.SearchRequest)
  })
_sym_db.RegisterMessage(SearchRequest)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'summa.proto.search_service_pb2'
  # @@protoc_insertion_point(class_scope:summa.proto.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)

_SEARCHAPI = DESCRIPTOR.services_by_name['SearchApi']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SCOREDDOCUMENT._serialized_start=49
  _SCOREDDOCUMENT._serialized_end=143
  _SEARCHREQUEST._serialized_start=145
  _SEARCHREQUEST._serialized_end=261
  _SEARCHRESPONSE._serialized_start=264
  _SEARCHRESPONSE._serialized_end=410
  _SEARCHAPI._serialized_start=412
  _SEARCHAPI._serialized_end=492
# @@protoc_insertion_point(module_scope)
