[build-system]
requires = [
    "setuptools>=45.0",
    "setuptools_scm[toml]>=4.2.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/intake_awkward/_version.py"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-v", "-ra", "--showlocals", "--strict-markers", "--strict-config"]
testpaths = ["tests"]

[tool.isort]
profile = "black"
line_length = 88
src_paths = ["src", "tests"]

[tool.mypy]
python_version = "3.8"
files = ["src"]
warn_unused_configs = true

[[tool.mypy.overrides]]
module = ["awkward.*"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["intake.*"]
ignore_missing_imports = true

[tool.pyright]
include = ["src"]
pythonVersion = "3.8"
