[tool.poetry]
name = "foresight"
version = "0.1.0"
description = "A simple tool to aid in tracking your time."
authors = ["ethan.schmitz <ethan.schmitz@mercuryds.com>"]

[tool.poetry.dependencies]
python = "^3.9"
cleo = "^0.8.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.17.0"
pytest = "^7.1.1"
tox = "^3.24.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
