[tool.poetry]
name = "render_engine"
version = "2022.03.02"
description = "Static Site Generator with a Flask-like flair"
authors = ["Jay Miller <kjaymiller@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.0"
markdown2 = "^2.4.2"
click = "^8.0.4"
pendulum = "^2.1.2"
progress = "^1.6"
more-itertools = "^8.12.0"
python-slugify = "^6.1.1"
darglint = "^1.8.1"
feedparser = "^6.0.8"
python-frontmatter = "^1.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
pytest-mock = "^3.7.0"
black = "^22.1.0"
isort = "^5.10.1"

[tool.isort]
profile = "black"
src_paths = ["isort", "test"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
