
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T13:00:40+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4fb290bab51675cedbb5c53c1f68623f4fbc3460",
 "version": "0.0.71.post0.dev78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
