# Generated by Django 3.0.3 on 2021-06-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlms_wms_public_table', '0003_supplier_bank_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'managed': False, 'verbose_name': '供应商公司', 'verbose_name_plural': '供应商公司'},
        ),
    ]
