
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-08-14T17:16:17-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5fd639977d4dc587b418c73b7aa4b1e83ab2d87",
 "version": "2.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
