
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T11:35:11+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "973aa08cbc44bc04117663b9ccd3f5b786a16707",
 "version": "0.4.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
