[dependencies]
env_logger = "0.9"
libm = "0.2"
log = "0.4"
ndarray-linalg = "0.14"
ndarray-npy = "0.8"
ndarray-rand = "0.14"
ndarray-stats = "0.5"
nlopt = "0.5.3"
rand_isaac = "0.3"
thiserror = "1"

[dependencies.doe]
path = "../doe"

[dependencies.finitediff]
features = ["ndarray"]
version = "0.1"

[dependencies.gp]
path = "../gp"

[dependencies.linfa]
features = ["intel-mkl-static"]
git = "https://github.com/relf/linfa.git"

[dependencies.linfa-pls]
default-features = false
git = "https://github.com/relf/linfa.git"

[dependencies.moe]
path = "../moe"

[dependencies.ndarray]
features = ["rayon", "approx", "blas"]
version = "0.15"

[dependencies.rawpointer]
version = "0.2"

[dev-dependencies]
approx = "0.4"
argmin_testfunctions = "0.1"
criterion = "0.3"
serde_json = "1"
serial_test = "*"

[dev-dependencies.linfa-datasets]
features = ["linnerud"]
git = "https://github.com/relf/linfa.git"

[lib]
name = "ego"

[package]
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"
name = "ego"
version = "0.1.0"
