[tool.poetry]
name = "pypika-tortoise"
version = "0.1.4"
description = "Forked from pypika and streamline just for tortoise-orm"
authors = ["long2ice <long2ice@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/tortoise/pypika-tortoise"
repository = "https://github.com/tortoise/pypika-tortoise.git"
documentation = "https://github.com/tortoise/pypika-tortoise"
keywords = ["postgresql", "Tortoise-ORM", "mysql", "sqlite", "sql"]
packages = [
    { include = "pypika" }
]
include = ["CHANGELOG.md", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
flake8 = "*"
isort = "*"
black = "*"
pytest = "*"
pylint = "*"
bandit = "*"
pytest-xdist = "*"
pytest-cov = "*"
twine = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
