# Generated by Django 3.1.6 on 2021-02-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={'ordering': ('-created',), 'verbose_name': 'respondent', 'verbose_name_plural': 'respondents'},
        ),
        migrations.AlterField(
            model_name='voter',
            name='hash_key',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='hash key'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='is_irrelevant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='irrelevant'),
        ),
    ]
