# Generated by Django 3.1.6 on 2022-02-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20210211_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='language',
            field=models.CharField(choices=[('sk', 'Slovak'), ('en', 'English'), ('hu', 'Hungarian'), ('pl', 'Polish'), ('cs', 'Czech')], max_length=2, verbose_name='language'),
        ),
        migrations.AddConstraint(
            model_name='voter',
            constraint=models.UniqueConstraint(condition=models.Q(voting_ended=None), fields=('survey', 'user'), name='unique_user_survey_voter'),
        ),
    ]
