# Generated by Django 3.1.6 on 2022-02-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20220225_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='voting_started',
            field=models.DateTimeField(verbose_name='voting started'),
        ),
    ]
