# Generated by Django 3.1.6 on 2022-02-25 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_auto_20220225_1001'),
        ('voting', '0004_auto_20220225_0954'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votedquestion',
            unique_together={('voter', 'question')},
        ),
    ]
