# Generated by Django 3.1.6 on 2022-02-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0013_auto_20220225_1001'),
        ('voting', '0005_auto_20220225_1001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('voter', 'question', 'option', 'option_column')},
        ),
    ]
