# Generated by Django 3.1.6 on 2022-02-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20220225_1007'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, custom=None), fields=('voter', 'question'), name='unique_voter_question_custom'),
        ),
    ]
