# Badge generation workflow
name: Badge
on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  coverage:
    runs-on: ubuntu-latest
    name: Coverage Test
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Obtain coverage number
        run: >
          tox -e coverage
          | awk '/^TOTAL\s+[0-9]+\s+[0-9]+\s+([0-9]+%)/ { print "COVERAGE="$4 }'
          >> $GITHUB_ENV
      - name: Create badge endpoint
        uses: schneegans/dynamic-badges-action@v1.1.0
        with:
          auth: ${{ secrets.CI_COVERAGE_BADGE_GIST }}
          gistID: 839011f3f7a6bab680b18cbd9a45d2d3
          filename: coverage-${{ github.ref_name }}.json
          label: coverage
          message: ${{ env.COVERAGE }}
          color: blue
