# Generated by Django 2.2.19 on 2021-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("films", "0011_auto_20200322_2311"),
    ]

    operations = [
        migrations.AlterField(
            model_name="film",
            name="imdb_rating",
            field=models.FloatField(blank=True, null=True, verbose_name="IMDB Rating"),
        ),
    ]
