
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T16:18:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7c1211eb59833cb529e074a36d06f58d3cf489c7",
 "version": "0.9.3rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
