
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T11:37:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c7d481ad344a40d87bf5b026cb33366f36c6801",
 "version": "0.7.1.post.dev471"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
