[tool.poetry]
name = "philter-lite"
version = "0.3.1"
description = ""
authors = ["Beau Norgeot <beaunorgeot@gmail.com>", "Tim Orme <tim@sironamedical.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.6.1"
chardet = "^3.0.4"
nltk = "^3.5"
xmltodict = "^0.12.0"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.7.1"
pytest = "^6.0.2"

[tool.poetry.scripts]
philter_lite = 'philter_lite.main:main'

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
