[tool.poetry]
  name = "tourscraper"
  version = "0.1.0"
  description = "Web scraper that aggregates tour dates in desired cities"
  authors = ["Dalton Black <projectdjswag@gmail.com>"]

[tool.poetry.scripts]
  tourscraper = "tourscraper.app:main"

[tool.poetry.dependencies]
  python = "^3.8"
  click = "^8.0.4"
  selenium = "^4.1.3"
  python-dotenv = "^0.20.0"

[tool.poetry.dev-dependencies]

[build-system]
  requires = ["poetry-core>=1.0.0"]
  build-backend = "poetry.core.masonry.api"
