[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "pynation"
author = "Abdulwasiu Apalowo"
author-email = "bazzanapalowo@gmail.com"
home-page = "https://github.com/mrbazzan/pynation/"
classifiers = [
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3.7",
        "Topic :: Software Development :: Libraries",
    ]
description-file="README.md"
requires = [
    "click==8.0.1",
]
requires-python=">=3.7"

[tool.flit.metadata.requires-extra]
dev = [
    "pytest==6.2.4",
]

[tool.flit.metadata.urls]
Documentation = "https://github.com/mrbazzan/pynation/blob/main/README.md"
Issues = "https://github.com/mrbazzan/pynation/issues"

[tool.flit.scripts]
pynation = "pynation.__main__:cli"
