
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T20:51:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "bdbd83fc915731094f1f2eec5b542a08ee5e076b",
 "version": "0.0.71.post0.dev94"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
