
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-25T22:25:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "007e63cf3b8fe6aee97ba6e53e897435512b74aa",
 "version": "0.3.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
