
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T18:16:18+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ba3f829a24b9538f232b3556df98192b44545424",
 "version": "0.0.71.post0.dev88"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
