[tool.poetry]
name = "pytailor"
version = "0.4.2"
description = "pyTailor orchestrates your existing python code as *workflows*"
authors = ["Audun Gravdal Johansen <audun@entail.no>"]
license = "BSD-3-Clause"
repository = "https://github.com/entailor/pytailor/"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.21.1"
click = "^8.0.3"
toml = "^0.10.1"
pydantic = "^1.5.1"
requests = "^2.24.0"
genson = "^1.2.2"
jsonpath-ng = "^1.5.2"

[tool.poetry.dev-dependencies]
datamodel-code-generator = "^0.11.15"
pytest = "^6.0.1"
pytest-cov = "^2.10.1"
pytest_httpx = "^0.17.3"
mkdocs-material = "^6.2.8"
pymdown-extensions = "^8.0"
pygments = "^2.6.1"
markdown = "^3.2.2"
mkautodoc = "^0.1.0"
nox = "^2020.8.22"

[tool.poetry.scripts]
tailor = 'pytailor.cli.main:cli'
[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"

