[tool.poetry]
name = "amap_distance_matrix"
version = "0.2.4"
description = "amap distance matrix service based on Redis and MySQL"
authors = ["Euraxluo <euraxluo@outlook.com>"]
license = "The MIT LICENSE"
readme = "README.md"
homepage = "https://github.com/Euraxluo/distance_matrix"
repository = "https://github.com/Euraxluo/distance_matrix"

[tool.poetry.dependencies]
python = "^3.7"
redis = "^4.1.4"
pydantic = "1.8.2"
aiohttp = "^3.8.1"
sqlalchemy-pydantic-orm = "^0.1.0"
polyline = "^1.4.0"
python-geohash = "^0.8.5"
PyMySQL = "^1.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
