
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-30T15:49:44-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec64967f76144f388a2796534de1ff620ede73df",
 "version": "0.21.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
