
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3c478036ae9edde3dd294af28bf1d8c78a2555d5",
 "version": "1.8.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
