[tool.poetry]
name = "sfdata-stream-tutorial"
version = "0.1.1"
description = ""
authors = ["Kaj Siebert <kaj@k-si.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
tablib = {extras = ["xlsx"], version = "^3.2.0"}
sfdata-stream-parser = "^0.2.0"
Faker = "^13.3.3"
click = "^8.0.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
