
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T13:51:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0af7beca2392cc4625dca5d8a8720a14792b4ea8",
 "version": "0.4.119"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
