# Generated by Django 3.2.5 on 2021-10-04 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0031_datatransformer_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformer',
            name='accessory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='data.accessory'),
        ),
    ]
