# Generated by Django 3.2.5 on 2021-10-06 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0041_auto_20211006_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('8cf96627-0b48-452b-876d-963fad0cbaf0'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardwarestatsdatatransformer',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('bcbc7600-e88b-4189-afaf-6efc6b11fcef'), primary_key=True, serialize=False),
        ),
    ]
