# Generated by Django 3.2.5 on 2021-10-07 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0045_auto_20211006_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hardwarestatsdatatransformer',
            name='index',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
