# Generated by Django 3.2.5 on 2021-11-04 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0047_alter_datatransformer_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='data_transformer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_transformer_constants', to='data.datatransformer'),
        ),
    ]
