# Generated by Django 3.2.5 on 2021-11-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0049_auto_20211105_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='data_transformer',
            field=models.ForeignKey(default='8275099d-6635-45c3-bcf0-c6acfe7a9b6a', on_delete=django.db.models.deletion.CASCADE, related_name='data_transformer_constants', to='data.datatransformer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='value',
            field=models.FloatField(),
        ),
    ]
