# Generated by Django 3.2.5 on 2021-07-21 04:57

from django.db import migrations

def gen(apps, schema_editor):
    from data.models.models import AccessoryType, HardwareChannelTypes, Category

    hardware_channel_types = [('AM2315', 'AM2315Humidity'),('AM2315', 'AM2315Temperature'),('PMSA0031', 'PMSA003125'),('PMSA0031', 'PMSA0031100')]

    for (hard, channel) in hardware_channel_types:
        cat = HardwareChannelTypes.objects.create()
        cat.hardware_type = hard
        cat.channel_type = channel
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0055_auto_20211215_2115'),
    ]

    operations = [
        migrations.RunPython(gen, reverse_code=migrations.RunPython.noop),
    ]
