# Generated by Django 3.2.9 on 2022-01-02 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0056_auto_20220102_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='AM2315',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.hardware')),
                ('scl', models.IntegerField()),
                ('sda', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.hardware',),
        ),
    ]
