# Generated by Django 3.2.5 on 2021-07-21 04:57

from django.db import migrations

def gen(apps, schema_editor):
    from data.models.models import AccessoryType, HardwareChannelTypes, Category

    hardware_channel_types = [('AdafruitStepperMotorHAT', 'AdafruitStepperMotor')]

    for (hard, channel) in hardware_channel_types:
        cat = HardwareChannelTypes.objects.create()
        cat.hardware_type = hard
        cat.channel_type = channel
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0062_auto_20220323_2208'),
    ]

    operations = [
        migrations.RunPython(gen, reverse_code=migrations.RunPython.noop),
    ]
