# Generated by Django 3.0.3 on 2021-06-08 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tlms_wms_public_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': '供应商公司', 'verbose_name_plural': '供应商公司'},
        ),
    ]
