# Generated by Django 3.0.3 on 2021-06-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tlms_wms_public_table', '0002_auto_20210608_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='bank_no',
            field=models.CharField(blank=True, help_text='银行编码', max_length=40, null=True, verbose_name='银行编码'),
        ),
    ]
