
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-30T10:32:36-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "35683bf2aadb5b280bf559c0a67c5813e0263737",
 "version": "2022.3.30"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
