
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-30T11:23:30+0200",
 "dirty": true,
 "error": null,
 "full-revisionid": "fc662a3e8cf0e8096cf4672f794463059cc5de79",
 "version": "0.2.41"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
