
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T14:20:08-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "39a7c1b52eb1df02b92feacd640e5d3f6873b357",
 "version": "0.1.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
