
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T00:12:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf20fe1137079f418d6a20cabab2788a7390a287",
 "version": "0.0.71.post0.dev32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
