
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T17:58:49+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "94ea2b323a93b087f69d197ce4774c53c2fbed04",
 "version": "0.0.71.post0.dev58"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
