
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-30T14:58:56+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "131df2af742e83bb72fc4a87a42bd5fa01a60108",
 "version": "0.4.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
