[tool.poetry]
name = "kabutobashi"
version = "0.3.2"
description = ""
authors = ["yoshiki <yoshiki0911@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
pandas = "^1.0.3"
requests = "^2.23.0"
beautifulsoup4 = "^4.9.0"
lxml = "^4.6.5"
jpholiday = "^0.1.1"
s3fs = "2021.11.0"
matplotlib = "^3.3.4"
mplfinance = "^0.12.7-alpha.7"
Cerberus = "^1.3.4"
scipy = "^1.8.0"

[tool.poetry.dev-dependencies]
myst-parser = "^0.15.2"
isort = "^5.9.3"
black = "^21.9b0"
jupyterlab = "^2.1.0"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
twine = "^3.1.1"
wheel = "^0.34.2"
sphinx = "^3.1.1"
sphinx_rtd_theme = "^0.5.0"
guzzle_sphinx_theme = "^0.7.11"
mypy = "^0.910"
sphinxcontrib-mermaid = "^0.7.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
target-version = ['py39']
line-length = 120
exclude = """
/(
    .git
    | .venv
    | .mypy_cache
    | .pytest_cache
    | data
    | docs
    | htmlcov
    | notebook
/)
"""

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
profile = "black"

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = true