input: ["img"]
output: ["bboxes", "bbox_labels", "bbox_scores"]

model_type: v4 # v4 or v4tiny
weights_parent_dir: null
weights: {
    model_subdir: yolo_license_plate,
    blob_file: yolo_license_plate.zip,
    classes_file: classes.names,
    saved_model_subdir: {
        v4: LPyolov4,
        v4tiny: LPyolov4tiny
    }
}
size: 416
max_output_size_per_class: 50
max_total_size: 50
iou_threshold: 0.3
score_threshold: 0.1
