[tool.poetry]
name = "crosslingual-coreference"
version = "0.1.2"
description = "A multi-lingual approach to AllenNLP CoReference Resolution, along with a wrapper for spaCy."
authors = ["David Berenstein <david.berenstein@pandoraintelligence.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pandora-intelligence/crosslingual-coreference"
repository = "https://github.com/pandora-intelligence/crosslingual-coreference"
documentation = "https://github.com/pandora-intelligence/crosslingual-coreference"
keywords = ["AllenNLP", "spaCy", "NLP"]
classifiers = [
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = ">=3.7.1,<4.0"
allennlp = ">=2.7,<2.9"
allennlp-models = ">=2.7,<2.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
