[tool.poetry]
name = "senka"
version = "0.1.0"
description = "making journal for transactions on blockchain"
authors = ["settler"]

[tool.poetry.dependencies]
python = "^3.8"
web3 = "^5.28.0"
bscscan-python = "^2.0.0"
pandas = "^1.4.1"
senkalib = "latest"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
pytest-cov = "^3.0.0"


[senka.plugin]
senka_plugin = []
