[build-system]
requires = ["poetry_core>=1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = 'blitskrieg'
version = '0.2.1'
description = 'The Bitcoin Lightning Integration Test Service'
license = 'AGPL-3.0-or-later'
authors = ['Hashbeam <hashbeam@protonmail.com>']
readme = 'README.md'
repository = 'https://gitlab.com/hashbeam/blitskrieg'
keywords = ['ln', 'lightning network', 'bitcoin', 'integration', 'test', 'boltlight']
classifiers = [
    'Development Status :: 4 - Beta',
    'Intended Audience :: Developers',
    'Natural Language :: English',
    'Operating System :: MacOS',
    'Operating System :: POSIX :: Linux',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Topic :: Other/Nonlisted Topic',
]

[tool.poetry.dependencies]
python = "^3.9.0"
click = "^8.0.4"
docker-compose = "^1.28.5"
googleapis-common-protos = "^1.53.0"
grpcio = "^1.43.0"
boltlight-proto = "^2.0.0"
PyYAML = "^5.4.1"
protobuf = "^3.19.1"
requests = "^2.25.1"
docker = "^5.0.3"

[tool.poetry.dev-dependencies]
click = "^8.0.4"
grpcio = "^1.43.0"
grpcio-tools = "^1.43.0"
isort = "^5.10.1"
pylint = "^2.12.2"
pylint-protobuf = "^0.20.2"
yapf = "^0.32.0"

[tool.poetry.scripts]
blitskrieg = 'blitskrieg.blitskrieg:start'
bli = 'blitskrieg.bli:entrypoint'

[tool.isort]
filter_files = true
include_trailing_comma = false
multi_line_output = 4
skip = ['blitskrieg/blitskrieg_pb2.py', 'blitskrieg/blitskrieg_pb2_grpc.py']

[tool.yapf]
based_on_style = 'pep8'
split_penalty_import_names = 1000

[tool.yapfignore]
ignore_patterns = [
  'blitskrieg/blitskrieg_pb2.py',
  'blitskrieg/blitskrieg_pb2_grpc.py',
]
