[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.coverage.paths]
source = ["nbdocs", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["nbdocs"]

[tool.coverage.report]
show_missing = true