name: Sync multiple branches
on:
  pull_request:
    branches:
      - master
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> brainpy-2.x
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: brainpy-2.x
          github_token: ${{ github.token }}