[[bench]]
harness = false
name = "gp"

[dependencies]
cobyla = "0.1.2"
ndarray-linalg = "0.14"
ndarray-npy = "0.8"
ndarray-rand = "0.14"
ndarray-stats = "0.5"
ndarray_einsum_beta = "0.7"
nlopt = "0.5.3"
num-traits = "0.2"
paste = "1.0"
rand_isaac = "0.3"
thiserror = "1"

[dependencies.doe]
path = "../doe"

[dependencies.linfa]
features = ["intel-mkl-static"]
git = "https://github.com/relf/linfa.git"

[dependencies.linfa-pls]
default-features = false
git = "https://github.com/relf/linfa.git"

[dependencies.ndarray]
features = ["rayon", "approx", "serde"]
version = "0.15"

[dependencies.serde]
features = ["derive"]
version = "1"

[dev-dependencies]
approx = "0.4"
argmin_testfunctions = "0.1"
criterion = "0.3"
serde_json = "1"

[lib]
name = "gp"

[package]
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"
name = "gp"
version = "0.1.0"
