[tool.poetry]
name = "Hitler"
version = "0.1.2"
description = "this is random code unnecessary"
authors = ["Gourav Saini"]
packages = [
    { include = "gourav" }
    ]

[tool.poetry.dependencies]
python = "^3.8"
[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"



