[dependencies]
bitflags = "1.3"
env_logger = "0.9"
log = "0.4"
ndarray-linalg = "0.14"
ndarray-npy = "0.8"
ndarray-rand = "0.14"
ndarray-stats = "0.5"
paste = "1.0"
rand_isaac = "0.3"
serde = "1"
serde_json = "1.0.73"
thiserror = "1"

[dependencies.doe]
path = "../doe"

[dependencies.gp]
path = "../gp"

[dependencies.linfa]
features = ["intel-mkl-static"]
git = "https://github.com/relf/linfa.git"

[dependencies.linfa-clustering]
default-features = false
git = "https://github.com/relf/linfa.git"

[dependencies.linfa-pls]
default-features = false
git = "https://github.com/relf/linfa.git"

[dependencies.ndarray]
features = ["rayon", "approx", "blas"]
version = "0.15"

[dev-dependencies]
approx = "0.4"
criterion = "0.3"
csv = "1.1"
ndarray-csv = "0.5"
ndarray-npy = "0.8"
serde_json = "1"

[lib]
name = "moe"

[package]
authors = ["relf <remi.lafage@onera.fr>"]
edition = "2018"
name = "moe"
version = "0.1.0"
