[tool.poetry]
name = "add2numbers-JamesBond"
version = "0.1.0"
description = "add two numbers"
authors = ["James Bond <JamesBond07@gmail.com>"]
readme = "README.md"
license = "MIT"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
