# Generated by Django 2.2.24 on 2021-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0008_vertical_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='minute',
            name='last_published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
