# Generated by Django 2.2.24 on 2021-08-23 15:35

import concurrency.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0010_minute_ready_to_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', concurrency.fields.AutoIncVersionField(default=0, help_text='record revision number')),
                ('lede', models.CharField(max_length=100)),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('campaign_title', models.CharField(blank=True, max_length=100, null=True)),
                ('campaign_link', models.URLField(blank=True, null=True)),
                ('pixels', models.TextField(blank=True, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ads', related_query_name='ads', to='minutes.Sponsor')),
            ],
        ),
    ]
