[tool.poetry]
name = "house-prices"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
sklearn-transformer-extensions = "^0.2.2"
ipdb = "^0.13.9"
matplotlib = "^3.5.1"
seaborn = "^0.11.2"
ipython = "^8.1.1"
category-encoders = "^2.4.0"
xgboost = "^1.5.2"
lightgbm = "^3.3.2"
catboost = "^1.0.4"
optuna = "^2.10.0"
plotly = "^5.6.0"
eli5 = "^0.11.0"
jupyter = "^1.0.0"
scikit-learn = "^1.0.2"
pandas-profiling = "^3.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["house_prices"]
venv = ".venv"
venvPath = "."

reportMissingImports = true
reportMissingTypeStubs = false
reportPrivateImportUsage = false
useLibraryCodeForTypes = true

pythonVersion = "3.8"
pythonPlatform = "Linux"

executionEnvironments = [{ root = "house_prices" }]

[tool.yapf]
split_before_named_assigns=false
allow_split_before_dict_value=false
column_limit=80

[tool.pytest.ini_options]
addopts="--pdbcls=IPython.terminal.debugger:TerminalPdb --doctest-modules --doctest-glob='*.md'"
