[tool.poetry]
name = "rushmore-tools"
version = "0.1.2"
description = ""
authors = ["Marcus Risanger <69350948+MarcusRisanger@users.noreply.github.com>"]
readme = "README.md"
homepage = "https://github.com/THREE60-Energy/rushmore-tools"
repository = "https://github.com/THREE60-Energy/rushmore-tools"
license = "Apache-2.0"
include = [
    "LICENSE",
]


[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
isort = "^5.10.1"
coverage = "^6.3.2"
requests-mock = "^1.9.3"
pylint = "^2.13.4"
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
