repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
    -   id: isort
-   repo: https://github.com/psf/black
    rev: 21.5b2
    hooks:
    -   id: black
        args: [--line-length=110]
-   repo: https://gitlab.com/PyCQA/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
-   repo: https://github.com/kynan/nbstripout
    rev: 0.4.0
    hooks:
    -   id: nbstripout
        files: ".ipynb"
