
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-28T09:07:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "376c3d5d2652581efd961434adb8cb8af00da3a6",
 "version": "1.16.0.post.dev332"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
