
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-29T15:03:27+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f293aecd04e17d1e09f28f616ef9d361e89aacce",
 "version": "0.4.120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
