
[build-system]
requires = [
    "setuptools>=43",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "-rxXs"
asyncio_mode = "strict"
# log_cli = true
# log_cli_level = "DEBUG"