[tool.poetry]
name = "nr.util"
version = "0.8.8"
description = "General purpose Python utility library."
authors = ["Niklas Rosenstein <rosensteinniklas@gmail.com>"]
license = "MIT"
readme = "readme.md"
homepage = "https://github.com/NiklasRosenstein/python-nr.util"
packages = [{ include="nr/util", from="src" }]

  [tool.poetry.dependencies]
  python = "^3.7"
  deprecated = "^1.2.0"
  typing-extensions = ">=3.0.0"

  [tool.poetry.extras]
  config = ["databind.json ^1.3.2"]

  [tool.poetry.dev-dependencies]
  "databind.json" = "^1.3.2"
  mypy = "^0.931"
  pandas = "*"
  pytest = "^6.2.5"
  PyYAML = "*"
  types-deprecated = "^1.2.0"
  types-python-dateutil = "*"
  types-setuptools = "^57.4.9"
  types-PyYAML = "*"

[tool.slap]
typed = true

[tool.slap.test]
pytest = "pytest test/"
mypy = "MYPYPATH=src mypy src test --namespace-packages --explicit-package-bases"
check = "slap check"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
