[tool.poetry]
name = "dgraph-orm"
version = "0.2.10"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]
exclude = ["tests/**/*"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26"
pydantic = {extras = ["email"], version = "^1.9.0"}
devtools = "^0.8"
fastapi = "*"
black = "^21.9b0"
httpx = "^0.19.0"
gql = {version = "^3.0.0b0", extras = ["all"]}
retry = "^0.9.2"
PyJWT = "*"
orjson = "^3.6.7"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
edgedb = "^0.22"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
