
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T15:12:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "51e85704ac4e928d2e357b6c8654021e6ba0ea3a",
 "version": "2022.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
