"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest
from unittest.mock import MagicMock

import MergeAccountingClient
from MergeAccountingClient.model.classification_enum import ClassificationEnum
from MergeAccountingClient.api_client import ApiClient


class TestClassificationEnum(unittest.TestCase):
    """ClassificationEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClassificationEnum(self):
        """Test ClassificationEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ClassificationEnum()  # noqa: E501

        # no tests for enums
        pass

if __name__ == '__main__':
    unittest.main()
