"""
    Merge Accounting API

    The unified API for building rich integrations with multiple Accounting & Finance platforms.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: hello@merge.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

import MergeAccountingClient
from MergeAccountingClient.api.report_items_api import ReportItemsApi  # noqa: E501


class TestReportItemsApi(unittest.TestCase):
    """ReportItemsApi unit test stubs"""

    def setUp(self):
        self.api = ReportItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_report_items_retrieve(self):
        """Test case for report_items_retrieve

        """
        pass


if __name__ == '__main__':
    unittest.main()
