
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2022-03-25T13:43:57-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbec66e967997e64096e3f67464624a7c4bcff1d",
 "version": "2.3.0.dev3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
