# Generated by Django 3.2.5 on 2021-08-14 18:37

from django.db import migrations

def gen(apps, schema_editor):
    from data.models.models import AccessoryType, HardwareChannelTypes, Category

    types = ['ACCurrent']

    for type in types:
        cat = AccessoryType.objects.create()
        cat.type = type
        cat.save()

    hardware_channel_types = [('PiPico', 'PiPicoACAnalog')]

    for (hard, channel) in hardware_channel_types:
        cat = HardwareChannelTypes.objects.create()
        cat.hardware_type = hard
        cat.channel_type = channel
        cat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20210924_2039'),
    ]

    operations = [
        migrations.RunPython(gen, reverse_code=migrations.RunPython.noop),
    ]