# Generated by Django 3.2.5 on 2021-10-06 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0040_auto_20211006_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b77fa90a-6def-4ca9-a1b2-9ec5a4424228'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardwarestatsdatatransformer',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('079bc0cc-9750-4e32-a08a-86ecfb77f267'), primary_key=True, serialize=False),
        ),
    ]
