# Generated by Django 3.2.5 on 2021-10-06 18:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0042_auto_20211006_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformerconstants',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('b6b46396-87ce-4a6e-9b19-1d8cb8327e81'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hardwarestatsdatatransformer',
            name='id',
            field=models.UUIDField(blank=True, default=uuid.UUID('6367f952-1c0f-4f22-a6aa-584e0be536ab'), primary_key=True, serialize=False),
        ),
    ]
