# Generated by Django 3.2.5 on 2021-10-08 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0046_auto_20211007_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformer',
            name='accessory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.accessory'),
        ),
    ]
