# Generated by Django 3.2.5 on 2021-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0052_auto_20211110_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransformer',
            name='channel_stats',
            field=models.ManyToManyField(blank=True, null=True, to='data.ChannelStats'),
        ),
        migrations.AlterField(
            model_name='datatransformer',
            name='channels',
            field=models.ManyToManyField(blank=True, null=True, to='data.Channel'),
        ),
    ]
