# Generated by Django 3.2.9 on 2021-12-15 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0054_auto_20211212_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.hardware')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.hardware',),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.CharField(choices=[('DHT22', 'Dht22'), ('MCP3008', 'Mcp3008'), ('ModProbe', 'Modprobe'), ('PiPico', 'Pipico'), ('Pi', 'Pi'), ('VEML7700', 'Veml7700')], default='PiPico', max_length=10),
        ),
    ]
