# Generated by Django 3.2.9 on 2022-01-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0057_am2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.CharField(choices=[('DHT22', 'Dht22'), ('MCP3008', 'Mcp3008'), ('ModProbe', 'Modprobe'), ('PiPico', 'Pipico'), ('Pi', 'Pi'), ('VEML7700', 'Veml7700'), ('PMSA0031', 'Pmsa0031'), ('AM2315', 'Am2315')], default='PiPico', max_length=10),
        ),
    ]
