# Generated by Django 3.2.11 on 2022-03-23 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0061_auto_20220128_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdafruitStepperMotorHAT',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.hardware')),
                ('scl', models.IntegerField()),
                ('sda', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.hardware',),
        ),
        migrations.CreateModel(
            name='StepperMotor',
            fields=[
                ('hardwareio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='data.hardwareio')),
                ('full_rotation_steps', models.IntegerField()),
                ('number_of_rotations', models.FloatField()),
                ('step_pause_time', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('data.hardwareio',),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.CharField(choices=[('DHT22', 'Dht22'), ('MCP3008', 'Mcp3008'), ('ModProbe', 'Modprobe'), ('PiPico', 'Pipico'), ('Pi', 'Pi'), ('VEML7700', 'Veml7700'), ('AdafruitStepperMotorHAT', 'Adafruitsteppermotorhat'), ('PMSA0031', 'Pmsa0031'), ('AM2315', 'Am2315')], default='PiPico', max_length=30),
        ),
        migrations.AlterField(
            model_name='hardwareio',
            name='type',
            field=models.CharField(choices=[('SPI', 'SPI'), ('Serial', 'Serial'), ('PWM', 'PWM'), ('I2C', 'I2C'), ('Device File', 'Device File'), ('MCP Channel', 'MCP Channel'), ('Pi Pico Analog', 'Pi Pico Analog'), ('Pi Pico AC Analog', 'Pi Pico AC Analog'), ('Pi GPIO', 'Pi GPIO'), ('Stepper Motor', 'Stepper Motor')], default='Pi Pico Analog', max_length=25),
        ),
    ]
