
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-31T11:47:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "14d83b6582a78df4f3e7e3ecad1a332189cdf119",
 "version": "0.7.1.post.dev489"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
