[tool.poetry]
name = "sirena"
version = "0.1.1-2"
description = ""
authors = ["Sam Phinizy <nipper@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.9.0"
tox = "^3.24.5"
importlib-metadata = { version = "0.12', ", python = "<3.8" }
luigi = { version = "^3.0.3", optional = true }
typer = "^0.4.1"

[tool.poetry.dev-dependencies]
black = "^22.1.0"
pytest = "^7.1.1"
pre-commit = "^2.17.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
luigi=['luigi']

[tool.poetry.scripts]
sirena = 'sirena.bin.cli:app'