[tool.poetry]
name = "pygrove"
version = "0.1.3-alpha.0"
description = "Common data science imports based on pyforest, with a NLP focus"
authors = ["sileod <damien.sileo@gmail.com>"]
include = ['pygrove/src/__init__.py']

[tool.poetry.dependencies]
python = "^3.7"
pyforest = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
