[tool.poetry]
name = "transmit"
version = "0.1.3"
description = "Transmit Server & Client use thrift"
authors = ["hbh112233abc <hbh112233abc@163.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/hbh112233abc/py-transmit"
repository = "https://github.com/hbh112233abc/py-transmit"
documentation = "https://github.com/hbh112233abc/py-transmit"
keywords = ["thrift", "transmit","json"]

[tool.poetry.dependencies]
python = "^3.7"
thrift = "^0.15.0"
loguru = "^0.6.0"
pretty-errors = "^1.2.25"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
