from .blocks import ViewBlock as AuthViewBlock
from .blocks import FileBlock as AuthFileBlock
from .blocks import LoginBlock as AuthLoginBlock
from .blocks import LogoutBlock as AuthLogoutBlock
from .blocks import PrepExecBlock as AuthPrepExecBlock
from .blocks import RegisterBlock as AuthRegisterBlock
from .blocks import RenewBlock as AuthRenewBlock
from .blocks import ResetBlock as AuthResetBlock
from .blocks import RemoveBlock as AuthRemoveBlock
