name: pytests

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  pytest:
    name: python${{ matrix.python-version }}-${{ matrix.platform.python-architecture }} ${{ matrix.platform.os }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      max-parallel: 16
      matrix:
        python-version: [3.7, 3.8, 3.9]
        platform: [
          { os: "ubuntu-latest", python-architecture: "x64", rust-target: "x86_64-unknown-linux-gnu", 
            rust-flags: "-C link-arg=-llapacke -C link-arg=-lcblas" },
          { os: "windows-latest", python-architecture: "x64", rust-target: "x86_64-pc-windows-msvc", 
            rust-flags: "" },
       ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - run: rustup set default-host ${{ matrix.platform.rust-target }}

      - name: Install Blas/Lapack on Ubuntu
        if: ${{ matrix.platform.os == 'ubuntu-latest' }} 
        run: sudo apt-get install libssl-dev gfortran libopenblas-dev liblapack-dev liblapacke-dev libatlas-base-dev

      - name: Install LLVM and Clang on Windows
        if: ${{ matrix.platform.os == 'windows-latest' }} 
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          directory: ${{ runner.temp }}/llvm

      - name: Build with default features
        run: cargo build --release
        env:
          RUSTFLAGS: ${{ matrix.platform.rust-flags }}

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install maturin numpy pytest poetry

      - name: Test Python
        run: |
            poetry install
            poetry run maturin develop --release
            poetry run pytest
        shell: bash
        env:
          RUSTFLAGS: ${{ matrix.platform.rust-flags }} 

    env:
      RUST_BACKTRACE: 1
