[tool.poetry]
name = "pytamaro-extra"
version = "0.1.0"
description = "Extra functionalities for PyTamaro"
authors = ["Luca Chiodini <luca@chiodini.org>"]

[tool.poetry.dependencies]
python = "^3.7"
pytamaro = "^0.1.1"
skia-python = "^87.4"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pylint = "^2.13.3"
pyright = "^1.1.233"
pycodestyle = "^2.8.0"
Sphinx = "^4.5.0"
sphinx-rtd-theme = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["pytamaro_extra", "tests"]

[tool.pytest.ini_options]
python_functions = "test_*"

[tool.pylint.MASTER]
extension-pkg-allow-list = "skia"
