
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-03-24T15:46:06-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "0cad8a97909a79d4e3abd891ed39f799c7ea7b7b",
 "version": "0.9.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
